version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    ECR_REPOSITORY_URI: "767397952451.dkr.ecr.ap-south-1.amazonaws.com/my-demo-app"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - echo "Docker login completed"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-demo-app .
      - docker tag my-demo-app:latest $ECR_REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - echo Docker image pushed successfully!

artifacts:
  files:
    - '**/*'
