name: Push Code to S3

on:
  push:
    branches:
      - main  # Change if you use a different branch

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Zip project
      run: zip -r my-demo-app.zip .

    - name: Upload to S3
      run: aws s3 cp my-demo-app.zip s3://my-demo-codepipeline-source/my-demo-app.zip

