name: Upload Project to S3

on:
  push:
    branches:
      - main  # Or your deploy branch

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Zip the project folder
      run: |
        zip -r project.zip . -x ".git/*"

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --delete --exclude "*" --include "project.zip"
      env:
        AWS_S3_BUCKET: ecs-fargate-code-997420041
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-2
