name: Zip and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Zip the project folder
      run: |
        mkdir upload
        zip -r upload/ci-demo-app.zip . -x ".git/*" ".github/*" "upload/*"
        ls -la

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --delete
      env:
        AWS_S3_BUCKET: ecs-fargate-code-997420041
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-2
